swagger: "3.0"
info:
  title: Microservicio de Cuentas Bancarias
  version: 1.0.0
  description: API para gestionar cuentas bancarias.

paths:
  /cuentas_bancarias/{cuenta_id}:
    get:
      summary: Obtener información de una cuenta bancaria
      parameters:
        - name: cuenta_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Información detallada de la cuenta bancaria.

  /cuentas_bancarias:
    post:
      summary: Crear una nueva cuenta bancaria
      parameters:
        - name: Cuenta Bancaria
          in: body
          required: true
          schema:
            $ref: "#/definitions/CuentaBancaria"
      responses:
        201:
          description: Cuenta bancaria creada con éxito.

  /cuentas_bancarias/{cuenta_id}:
    put:
      summary: Actualizar información de una cuenta bancaria
      parameters:
        - name: cuenta_id
          in: path
          required: true
          type: string
        - name: Cuenta Bancaria
          in: body
          required: true
          schema:
            $ref: "#/definitions/CuentaBancaria"
      responses:
        200:
          description: Información de la cuenta bancaria actualizada.

  /cuentas_bancarias/{cuenta_id}:
    delete:
      summary: Eliminar una cuenta bancaria
      parameters:
        - name: cuenta_id
          in: path
          required: true
          type: string
      responses:
        204:
          description: Cuenta bancaria eliminada con éxito.

  /cuentas_bancarias/{cuenta_id}/depositos:
    post:
      summary: Realizar un depósito en una cuenta bancaria
      parameters:
        - name: cuenta_id
          in: path
          required: true
          type: string
        - name: Monto
          in: body
          required: true
          schema:
            $ref: "#/definitions/MontoDeposito"
      responses:
        200:
          description: Depósito realizado con éxito.

  /cuentas_bancarias/{cuenta_id}/retiros:
    post:
      summary: Realizar un retiro desde una cuenta bancaria
      parameters:
        - name: cuenta_id
          in: path
          required: true
          type: string
        - name: Monto
          in: body
          required: true
          schema:
            $ref: "#/definitions/MontoRetiro"
      responses:
        200:
          description: Retiro realizado con éxito.

  /cuentas_bancarias/{cuenta_id}/movimientos:
    get:
      summary: Consultar movimientos de una cuenta bancaria
      parameters:
        - name: cuenta_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Lista de movimientos de la cuenta bancaria.

definitions:
  CuentaBancaria:
    type: object
    properties:
      cliente_id:
        type: string
      tipo_cuenta:
        type: string
        enum:
          - Ahorro
          - Cuenta Corriente
          - Plazo Fijo
      saldo:
        type: number


  MontoDeposito:
    type: object
    properties:
      monto:
        type: number


  MontoRetiro:
    type: object
    properties:
      monto:
        type: number

